### ISSUE TITLE
Denial of service following malformed dictionary request

### ISSUE THREAD

**Issue by mbooth101** [sheffgeeks/burritobot#1]
This command killed burritobot dead:

```
burritobot: define: "; drop table commands; --
```

**Comment by garym** [comment]
Catching exceptions from plugins and passing the tracebacks to logging for now in 491bbe6167
Could catch the exception earlier of course...
Feel free to test

**Comment by mbooth101** [comment]
Tested in #sheffgeeks, seems to now not crash :-)

**Comment by garym** [comment]
for further work, #3 is the appropriate issue
